#include "extensions.comp"

#include "common.comp"

#define VECTOR_STORAGE_LAYOUT_SET 1
#include "vector_storage.comp"

#define LINKS_LAYOUT_SET 2
#include "links.comp"

#define VISITED_FLAGS_LAYOUT_SET 3
#include "visited_flags.comp"

#include "search_context.comp"

struct SearchRequest {
    uint id;
    uint entry;
};

[[vk::binding(0, 0)]] StructuredBuffer<SearchRequest> search_requests;
[[vk::binding(1, 0)]] RWStructuredBuffer<ScoredPoint> search_results;

[shader("compute")]
[numthreads(SUBGROUP_SIZE, 1, 1)]
void main(uint3 dtid : SV_DispatchThreadID) {
    gl_GlobalInvocationID = dtid;
    search_context_init();
    uint subgroup_index = SUBGROUP_ID;
    SearchRequest search_request = search_requests[subgroup_index];

    set_target(search_request.id);
    float entry_score = similarity(search_request.entry);
    uint count = search(search_request.id, ScoredPoint(search_request.entry, entry_score));

    GroupMemoryBarrierWithGroupSync();

    if (WaveIsFirstLane()) {
        uint result_index_offset = EF * subgroup_index;
        uint i = 0;
        for (; i < count; i++) {
            search_results[result_index_offset + i] = shared_buffer[NEAREST_HEAP_OFFSET + i];
        }
        for (; i < EF; i++) {
            search_results[result_index_offset + i] = ScoredPoint(UINT_MAX, 0.0);
        }
    }
}
