#include "extensions.comp"

#include "common.comp"

#define VECTOR_STORAGE_LAYOUT_SET 1
#include "vector_storage.comp"

[[vk::binding(0, 0)]] RWStructuredBuffer<float> scores;

[shader("compute")]
[numthreads(SUBGROUP_SIZE, 1, 1)]
void main(uint3 dtid : SV_DispatchThreadID) {
    gl_GlobalInvocationID = dtid;
    uint idx = SUBGROUP_ID;
    set_target(0);
    float score = similarity(idx);
    if (WaveIsFirstLane()) {
        scores[idx] = score;
    }
}
