#include "extensions.comp"

#include "common.comp"

#define SHARED_BUFFER_CAPACITY EF
#define NEAREST_HEAP_OFFSET 0

#include "shared_buffer.comp"
#include "bheap.comp"

struct TestParamsStruct {
    uint input_counts;
};

[[vk::binding(0, 0)]] ConstantBuffer<TestParamsStruct> test_params;
[[vk::binding(1, 0)]] StructuredBuffer<ScoredPoint> input_points;
[[vk::binding(2, 0)]] RWStructuredBuffer<float> scores_output;
[[vk::binding(3, 0)]] RWStructuredBuffer<uint> sorted_output;

static uint nearest_count = 0;

[shader("compute")]
[numthreads(SUBGROUP_SIZE, 1, 1)]
void main(uint3 dtid : SV_DispatchThreadID) {
    gl_GlobalInvocationID = dtid;
    uint subgroup_index = SUBGROUP_ID;

    for (uint i = 0; i < test_params.input_counts; i++) {
        uint point_index = subgroup_index * test_params.input_counts + i;
        ScoredPoint point = input_points[point_index];
        bheap_push(NEAREST_HEAP_OFFSET, nearest_count, EF, point);

        GroupMemoryBarrier();
        AllMemoryBarrier();

        float nearest_smaller_score_check = WaveActiveMin(bheap_top(NEAREST_HEAP_OFFSET).score);
        bool is_different = nearest_smaller_score_check != bheap_top(NEAREST_HEAP_OFFSET).score;
        if (WaveActiveAnyTrue(is_different)) {
            if (WaveIsFirstLane()) {
                scores_output[point_index] = positive_infinity;
            }
        } else if (WaveIsFirstLane()) {
            scores_output[point_index] = bheap_top(NEAREST_HEAP_OFFSET).score;
        }
    }

    sort(NEAREST_HEAP_OFFSET, nearest_count);
    if (WaveIsFirstLane()) {
        for (uint i = 0; i < EF; i++) {
            uint point_index = subgroup_index * EF + i;
            sorted_output[point_index] = shared_buffer[NEAREST_HEAP_OFFSET + i].id;
        }
    }
}
