#version 450
#pragma use_vulkan_memory_model

#include "extensions.comp"

#include "common.comp"
layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define VECTOR_STORAGE_LAYOUT_SET 1
#include "vector_storage.comp"

layout(set = 0, binding = 0) buffer ScoresData {
    float data[];
} scores;

void main() {
    uint idx = gl_WorkGroupID.x;
    set_target(0);
    float score = similarity(idx);
    if (gl_LocalInvocationID.x == 0) {
        scores.data[idx] = score;
    }
}
