storage:
  # Where to store all the data
  storage_path: /var/lib/qdrant/storage

  # Where to store snapshots
  snapshots_path: /var/lib/qdrant/snapshots

service:
  static_content_dir: /var/lib/qdrant/static

metrics:
  # Enable or disable per-collection granularity in Prometheus metrics
  record_per_collection: false
