// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: collections_internal_service.proto

package go_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCollectionInfoRequestInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetCollectionInfoRequest *GetCollectionInfoRequest `protobuf:"bytes,1,opt,name=get_collectionInfoRequest,json=getCollectionInfoRequest,proto3" json:"get_collectionInfoRequest,omitempty"`
	ShardId                  uint32                    `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
}

func (x *GetCollectionInfoRequestInternal) Reset() {
	*x = GetCollectionInfoRequestInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collections_internal_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollectionInfoRequestInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionInfoRequestInternal) ProtoMessage() {}

func (x *GetCollectionInfoRequestInternal) ProtoReflect() protoreflect.Message {
	mi := &file_collections_internal_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionInfoRequestInternal.ProtoReflect.Descriptor instead.
func (*GetCollectionInfoRequestInternal) Descriptor() ([]byte, []int) {
	return file_collections_internal_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCollectionInfoRequestInternal) GetGetCollectionInfoRequest() *GetCollectionInfoRequest {
	if x != nil {
		return x.GetCollectionInfoRequest
	}
	return nil
}

func (x *GetCollectionInfoRequestInternal) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

var File_collections_internal_service_proto protoreflect.FileDescriptor

var file_collections_internal_service_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x71, 0x64, 0x72, 0x61, 0x6e, 0x74, 0x1a, 0x11, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9c, 0x01, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x12, 0x5d, 0x0a, 0x19, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x71, 0x64, 0x72, 0x61, 0x6e, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x18, 0x67, 0x65, 0x74, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x32, 0x6b,
	0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x54, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x28, 0x2e, 0x71,
	0x64, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x1a, 0x21, 0x2e, 0x71, 0x64, 0x72, 0x61, 0x6e, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_collections_internal_service_proto_rawDescOnce sync.Once
	file_collections_internal_service_proto_rawDescData = file_collections_internal_service_proto_rawDesc
)

func file_collections_internal_service_proto_rawDescGZIP() []byte {
	file_collections_internal_service_proto_rawDescOnce.Do(func() {
		file_collections_internal_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_collections_internal_service_proto_rawDescData)
	})
	return file_collections_internal_service_proto_rawDescData
}

var file_collections_internal_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_collections_internal_service_proto_goTypes = []interface{}{
	(*GetCollectionInfoRequestInternal)(nil), // 0: qdrant.GetCollectionInfoRequestInternal
	(*GetCollectionInfoRequest)(nil),         // 1: qdrant.GetCollectionInfoRequest
	(*GetCollectionInfoResponse)(nil),        // 2: qdrant.GetCollectionInfoResponse
}
var file_collections_internal_service_proto_depIdxs = []int32{
	1, // 0: qdrant.GetCollectionInfoRequestInternal.get_collectionInfoRequest:type_name -> qdrant.GetCollectionInfoRequest
	0, // 1: qdrant.CollectionsInternal.Get:input_type -> qdrant.GetCollectionInfoRequestInternal
	2, // 2: qdrant.CollectionsInternal.Get:output_type -> qdrant.GetCollectionInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_collections_internal_service_proto_init() }
func file_collections_internal_service_proto_init() {
	if File_collections_internal_service_proto != nil {
		return
	}
	file_collections_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_collections_internal_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollectionInfoRequestInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collections_internal_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collections_internal_service_proto_goTypes,
		DependencyIndexes: file_collections_internal_service_proto_depIdxs,
		MessageInfos:      file_collections_internal_service_proto_msgTypes,
	}.Build()
	File_collections_internal_service_proto = out.File
	file_collections_internal_service_proto_rawDesc = nil
	file_collections_internal_service_proto_goTypes = nil
	file_collections_internal_service_proto_depIdxs = nil
}
