// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: collections_internal_service.proto

package go_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CollectionsInternalClient is the client API for CollectionsInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectionsInternalClient interface {
	Get(ctx context.Context, in *GetCollectionInfoRequestInternal, opts ...grpc.CallOption) (*GetCollectionInfoResponse, error)
}

type collectionsInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectionsInternalClient(cc grpc.ClientConnInterface) CollectionsInternalClient {
	return &collectionsInternalClient{cc}
}

func (c *collectionsInternalClient) Get(ctx context.Context, in *GetCollectionInfoRequestInternal, opts ...grpc.CallOption) (*GetCollectionInfoResponse, error) {
	out := new(GetCollectionInfoResponse)
	err := c.cc.Invoke(ctx, "/qdrant.CollectionsInternal/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectionsInternalServer is the server API for CollectionsInternal service.
// All implementations must embed UnimplementedCollectionsInternalServer
// for forward compatibility
type CollectionsInternalServer interface {
	Get(context.Context, *GetCollectionInfoRequestInternal) (*GetCollectionInfoResponse, error)
	mustEmbedUnimplementedCollectionsInternalServer()
}

// UnimplementedCollectionsInternalServer must be embedded to have forward compatible implementations.
type UnimplementedCollectionsInternalServer struct {
}

func (UnimplementedCollectionsInternalServer) Get(context.Context, *GetCollectionInfoRequestInternal) (*GetCollectionInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCollectionsInternalServer) mustEmbedUnimplementedCollectionsInternalServer() {}

// UnsafeCollectionsInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectionsInternalServer will
// result in compilation errors.
type UnsafeCollectionsInternalServer interface {
	mustEmbedUnimplementedCollectionsInternalServer()
}

func RegisterCollectionsInternalServer(s grpc.ServiceRegistrar, srv CollectionsInternalServer) {
	s.RegisterService(&CollectionsInternal_ServiceDesc, srv)
}

func _CollectionsInternal_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionInfoRequestInternal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionsInternalServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qdrant.CollectionsInternal/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionsInternalServer).Get(ctx, req.(*GetCollectionInfoRequestInternal))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectionsInternal_ServiceDesc is the grpc.ServiceDesc for CollectionsInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectionsInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qdrant.CollectionsInternal",
	HandlerType: (*CollectionsInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CollectionsInternal_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "collections_internal_service.proto",
}
