name: Install Just
description: "Install a pinned version of the just command runner"

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      with:
        just-version: "1.50.0"
