name: Build the Docker image
description: "Run benchmark with specified params"

runs:
  using: "composite"
  steps:
    - name: Execution
      shell: bash
      run: |
        buildx_containers=$(docker container ls -a -qf "name=buildx_buildkit" | tr '\n' ' ')
        buildx_volumes=$(docker volume ls -qf "name=buildx_buildkit" | tr '\n' ' ')
        
        if [ -n "$buildx_containers" ]; then
          echo "Buildx containers to delete: $buildx_containers"
          docker container rm -f $buildx_containers
        fi
        
        if [ -n "$buildx_volumes" ]; then
          echo "Buildx volumes to delete: $buildx_volumes"
          docker volume rm -f $buildx_volumes
        fi
        
        branch_tmp=$(git rev-parse --abbrev-ref HEAD)
        branch=${branch_tmp//\//-} # replace all / with -
        echo "Building branch $branch"
        
        # Create build container
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use
        
        # Authenticate on registries
        docker login https://ghcr.io -u qdrant --password ${{ secrets.GITHUB_TOKEN }}
        
        # Build regular image for Github Registry
        # use full git commit sha
        GIT_COMMIT_ID=$(git rev-parse HEAD)
        GITHUB_TAG="-t ghcr.io/qdrant/qdrant:$branch-${GIT_COMMIT_ID} -t ghcr.io/qdrant/qdrant:$branch"
        echo "Building tag $branch-${GIT_COMMIT_ID}"
        
        # Pull, retag and push to GitHub packages
        docker buildx build --platform='linux/amd64,linux/arm64' --build-arg GIT_COMMIT_ID="${GIT_COMMIT_ID}" "$GITHUB_TAG" --push --label "org.opencontainers.image.revision"="${GIT_COMMIT_ID}" .
