[profile.ci]
# Retry tests before failing them.
retries = { backoff = "exponential", count = 1, delay = "2s" }
# Do not cancel the test run on the first failure.
fail-fast = false
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"

# save junit report
[profile.ci.junit]
path = "junit.xml"

# The `test_hw_metrics_cancellation` test relies on a search timeout, which might
# not be scheduled at all if the CI runner's CPU pressure is too high.
# This is because `spawn_blocking` sometimes doesn't spawn a new worker thread before
# the test's search timeout is reached.
# To trick nextest into not running other tests in parallel, we override this test
# specifically and force it to get all CPUs allocated.
[[profile.default.overrides]]
filter = 'package(collection) and test(test_hw_metrics_cancellation)'
threads-required = "num-test-threads"
