#!/usr/bin/env bash
# Regenerate lib/src/qdrant_edge_ffi.dart from the `qdrant-edge-ffi` crate.
#
# The binding is generated in *library mode*: uniffi-bindgen-dart reads the
# UniFFI metadata embedded in a compiled cdylib (our crate uses
# `setup_scaffolding!()`, i.e. proc-macros and no UDL). `uniffi.toml` sets the
# Dart package name so the generated `@Native` asset ids match this package.
#
# Toolchain: `cargo +nightly ... --locked` is explicit (NOT relying on the
# rust-toolchain.toml override, which rustup only applies when cargo runs from
# at-or-below its directory — these scripts run cargo from the workspace root,
# an ancestor, where the override never fires). Matches build-xcframework.sh /
# build-aar.sh.
#
# Feature parity with the mobile Swift/Kotlin SDKs: `--no-default-features` drops
# the default `matrix` feature so `search_matrix` stays off the surface, exactly
# as the Swift/Kotlin bindgen builds do.
#
# The `uniffi_bindgen_dart` CLI must be built from the FORK that carries the
# uniffi-0.32 + library-mode-CLI + collision-fix work (upstream lacks them):
#   github.com/DenisovAV/uniffi-dart @ branch `library-mode-cli`
# Point UNIFFI_BINDGEN_DART at that build, or install it and put it on PATH.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
export PATH="$HOME/.cargo/bin:$PATH"

echo "==> Building qdrant-edge-ffi cdylib (host, nightly, --no-default-features)…"
( cd "$WORKSPACE_ROOT" && cargo +nightly build --locked --no-default-features -p qdrant-edge-ffi )

case "$(uname -s)" in
  Darwin) DYLIB="$WORKSPACE_ROOT/target/debug/libqdrant_edge_ffi.dylib" ;;
  *)      DYLIB="$WORKSPACE_ROOT/target/debug/libqdrant_edge_ffi.so" ;;
esac
[ -f "$DYLIB" ] || { echo "error: built cdylib not found at $DYLIB" >&2; exit 1; }

BINDGEN="${UNIFFI_BINDGEN_DART:-uniffi_bindgen_dart}"
command -v "$BINDGEN" >/dev/null 2>&1 || [ -x "$BINDGEN" ] || {
  echo "error: uniffi_bindgen_dart not found (set UNIFFI_BINDGEN_DART to the fork build)" >&2
  exit 1
}
echo "==> Generating Dart binding into lib/src/…"
"$BINDGEN" \
  --library "$DYLIB" \
  --out-dir "$SCRIPT_DIR/lib/src" \
  --config "$SCRIPT_DIR/uniffi.toml"

echo "==> Wrote $SCRIPT_DIR/lib/src/qdrant_edge_ffi.dart"

# Generate the curated public facade: export ONLY the domain types, never the
# UniFFI plumbing (FfiConverter*/Uniffi*/RustBuffer/… and the raw @Native C
# functions). Keeping this derived from the binding (rather than a hand-list)
# means a regenerated binding can't silently leak a new plumbing symbol into the
# public API, and the CI diff gate catches domain-surface changes.
echo "==> Generating curated public facade lib/qdrant_edge.dart…"
# Domain types: everything the binding declares, minus the UniFFI plumbing
# (FfiConverter*/Uniffi*/RustBuffer/Foreign*/LiftRetVal*/_private and the
# *ErrorHandler shims).
base_types="$(grep -oE '^(class|enum|abstract class|final class|sealed class|mixin|extension|typedef) [A-Za-z_][A-Za-z0-9_]*' \
    "$SCRIPT_DIR/lib/src/qdrant_edge_ffi.dart" \
  | awk '{print $NF}' \
  | grep -vE '^(FfiConverter|Uniffi|Rust|Foreign|LiftRetVal|_)|ErrorHandler$')"
# …plus the ONE plumbing type that is part of the public contract:
# `UniffiInternalError` is what `checkCallStatus` throws for a Rust panic or a
# bindings/native protocol mismatch (CALL_UNEXPECTED_ERROR), so it *can* cross
# the public boundary. It is the only exception a consumer cannot express as
# `EdgeException`, so we export it by name — that is what makes the README's
# "every exception crossing this API is catchable by name" guarantee true.
# Guarded on its presence so a future UniFFI rename can't emit a dangling export.
extra_types=""
if grep -qE '^class UniffiInternalError\b' "$SCRIPT_DIR/lib/src/qdrant_edge_ffi.dart"; then
  extra_types="UniffiInternalError"
fi
# UniFFI `#[uniffi::export] pub fn`s are emitted as TOP-LEVEL Dart functions, not
# types, so the type grep above never sees them. List the public ones explicitly
# (the plumbing top-levels — checkCallStatus/rustCall/… — stay unexported). Each
# is guarded on its generated declaration so a rename can't leave a dangling
# export; a NEW exported free function must be added to this list to reach the
# barrel.
free_fns=""
for fn in probeShard unpackSnapshot; do
  if grep -qE "^[A-Za-z_][A-Za-z0-9_<>,? ]* ${fn}\(" "$SCRIPT_DIR/lib/src/qdrant_edge_ffi.dart"; then
    free_fns="${free_fns}${fn}"$'\n'
  fi
done
types="$(printf '%s\n%s\n%s\n' "$base_types" "$extra_types" "$free_fns" | grep -v '^$' | sort -u)"
{
  cat <<'HEADER'
/// Qdrant Edge — on-device vector search for Dart and Flutter.
///
/// GENERATED by ./build.sh — do not edit. The public surface is curated: the
/// domain types, plus the one plumbing type that can cross the boundary —
/// [UniffiInternalError], thrown for a Rust panic or a bindings/native protocol
/// mismatch. The rest of the UniFFI plumbing in `src/` (`FfiConverter*`,
/// `RustBuffer`, the other `Uniffi*` internals, the raw `@Native` C functions)
/// is intentionally NOT exported, so it stays out of this package's semver
/// contract and a UniFFI bump can reshape it without breaking consumers.
///
/// Exporting [UniffiInternalError] is what makes the README's "Error handling"
/// guarantee hold: every exception crossing this API is catchable by name — an
/// [EdgeException] for a domain/engine error, or [UniffiInternalError] for a
/// bindings/native failure.
///
/// Entry point: [EdgeShard] — open with `EdgeShard.load(...)` /
/// `EdgeShard.create(...)`, then `update(...)` / `search(...)` / `query(...)`.
library;

export 'src/qdrant_edge_ffi.dart'
    show
HEADER
  printf '%s\n' "$types" | sed 's/^/        /' | sed '$!s/$/,/' | sed '$s/$/;/'
} > "$SCRIPT_DIR/lib/qdrant_edge.dart"
echo "==> Wrote $SCRIPT_DIR/lib/qdrant_edge.dart ($(printf '%s\n' "$types" | grep -c .) domain types)"
