# This file is auto-generated by `just py-stubs`
from __future__ import annotations
import typing
import uuid
from typing import TypeAlias
from collections.abc import Iterator, Sequence
from os import PathLike
from typing import Any, Final, final

@final
class AcornSearchParams:
    def __new__(
        cls, /, enable: bool = False, max_selectivity: float | None = None
    ) -> AcornSearchParams: ...
    def __repr__(self, /) -> str: ...
    @property
    def enable(self, /) -> bool: ...
    @property
    def max_selectivity(self, /) -> float | None: ...

@final
class BinaryQuantizationConfig:
    def __new__(
        cls,
        /,
        always_ram: bool | None = None,
        encoding: BinaryQuantizationEncoding | None = None,
        query_encoding: BinaryQuantizationQueryEncoding | None = None,
    ) -> BinaryQuantizationConfig: ...
    def __repr__(self, /) -> str: ...
    @property
    def always_ram(self, /) -> bool | None: ...
    @property
    def encoding(self, /) -> BinaryQuantizationEncoding | None: ...
    @property
    def query_encoding(self, /) -> BinaryQuantizationQueryEncoding | None: ...

@final
class BinaryQuantizationEncoding:
    OneAndHalfBits: Final[BinaryQuantizationEncoding]
    OneBit: Final[BinaryQuantizationEncoding]
    TwoBits: Final[BinaryQuantizationEncoding]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class BinaryQuantizationQueryEncoding:
    Binary: Final[BinaryQuantizationQueryEncoding]
    Default: Final[BinaryQuantizationQueryEncoding]
    Scalar4Bits: Final[BinaryQuantizationQueryEncoding]
    Scalar8Bits: Final[BinaryQuantizationQueryEncoding]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class Bm25:
    """
    BM25 sparse-vector embedding model. Construct once with a [`Bm25Config`],
    then call [`embed_query`] / [`embed_document`] to get sparse vectors.
    """

    def __new__(cls, /, config: Bm25Config | None = None) -> Bm25: ...
    def embed_document(self, /, text: str) -> SparseVector:
        """
        Embed `text` as an indexed document: term-frequency weights with `(k, b, avg_len)`.
        """

    def embed_query(self, /, text: str) -> SparseVector:
        """
        Embed `text` as a search query: each unique token gets weight 1.0.
        """

@final
class Bm25Config:
    """
    Configuration for an edge-side BM25 model.
    """

    def __new__(
        cls,
        /,
        k: float | None = None,
        b: float | None = None,
        avg_len: float | None = None,
        tokenizer: TokenizerType | None = None,
        language: str | None = None,
        lowercase: bool | None = None,
        ascii_folding: bool | None = None,
        stopwords: Stopwords | None = None,
        stemmer: StemmingAlgorithm | None = None,
        min_token_len: int | None = None,
        max_token_len: int | None = None,
    ) -> Bm25Config: ...
    @property
    def ascii_folding(self, /) -> bool | None: ...
    @property
    def avg_len(self, /) -> float: ...
    @property
    def b(self, /) -> float: ...
    @property
    def k(self, /) -> float: ...
    @property
    def language(self, /) -> str | None: ...
    @property
    def lowercase(self, /) -> bool | None: ...
    @property
    def max_token_len(self, /) -> int | None: ...
    @property
    def min_token_len(self, /) -> int | None: ...
    @property
    def stemmer(self, /) -> StemmingAlgorithm | None: ...
    @property
    def stopwords(self, /) -> Stopwords | None: ...
    @property
    def tokenizer(self, /) -> TokenizerType: ...

@final
class BoolIndexParams:
    def __new__(
        cls, /, on_disk: bool | None = None, enable_hnsw: bool | None = None
    ) -> BoolIndexParams: ...
    @property
    def enable_hnsw(self, /) -> bool | None: ...
    @property
    def on_disk(self, /) -> bool | None: ...

@final
class CompressionRatio:
    X16: Final[CompressionRatio]
    X32: Final[CompressionRatio]
    X4: Final[CompressionRatio]
    X64: Final[CompressionRatio]
    X8: Final[CompressionRatio]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class ContextPair:
    def __new__(
        cls, /, positive: NamedVector, negative: NamedVector
    ) -> ContextPair: ...
    def __repr__(self, /) -> str: ...
    @property
    def negative(self, /) -> NamedVector: ...
    @property
    def positive(self, /) -> NamedVector: ...

@final
class ContextQuery:
    def __new__(cls, /, pairs: Sequence[ContextPair]) -> ContextQuery: ...
    def __repr__(self, /) -> str: ...
    @property
    def pairs(self, /) -> list[ContextPair]: ...

@final
class CountRequest:
    def __new__(
        cls, /, exact: bool = True, filter: Filter | None = None
    ) -> CountRequest: ...
    @property
    def exact(self, /) -> bool: ...
    @property
    def filter(self, /) -> Filter | None: ...

@final
class DatetimeIndexParams:
    def __new__(
        cls,
        /,
        is_principal: bool | None = None,
        on_disk: bool | None = None,
        enable_hnsw: bool | None = None,
    ) -> DatetimeIndexParams: ...
    @property
    def enable_hnsw(self, /) -> bool | None: ...
    @property
    def is_principal(self, /) -> bool | None: ...
    @property
    def on_disk(self, /) -> bool | None: ...

@final
class DecayKind:
    Exp: Final[DecayKind]
    """
    Exponential decay function
    """
    Gauss: Final[DecayKind]
    """
    Gaussian decay function
    """
    Lin: Final[DecayKind]
    """
    Linear decay function
    """
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class Direction:
    Asc: Final[Direction]
    Desc: Final[Direction]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class DisabledStemmer:
    """
    Explicitly disable stemming, overriding the language default.
    """

    def __new__(cls, /) -> DisabledStemmer: ...

@final
class DiscoverQuery:
    def __new__(
        cls, /, target: NamedVector, pairs: Sequence[ContextPair]
    ) -> DiscoverQuery: ...
    def __repr__(self, /) -> str: ...
    @property
    def pairs(self, /) -> list[ContextPair]: ...
    @property
    def target(self, /) -> NamedVector: ...

@final
class Distance:
    Cosine: Final[Distance]
    Dot: Final[Distance]
    Euclid: Final[Distance]
    Manhattan: Final[Distance]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class EdgeConfig:
    def __new__(
        cls,
        /,
        vectors=None,
        sparse_vectors: dict[str, EdgeSparseVectorParams] | None = None,
        on_disk_payload: bool | None = None,
        hnsw_config: HnswIndexConfig | None = None,
        quantization_config: QuantizationConfigType | None = None,
        optimizers: EdgeOptimizersConfig | None = None,
        max_search_threads: int | None = None,
        search_pool_core: int | None = None,
    ) -> EdgeConfig: ...
    def __repr__(self, /) -> str: ...
    @property
    def hnsw_config(self, /) -> HnswIndexConfig | None: ...
    @property
    def max_search_threads(self, /) -> int | None: ...
    @property
    def on_disk_payload(self, /) -> bool | None: ...
    @property
    def optimizers(self, /) -> EdgeOptimizersConfig | None: ...
    @property
    def quantization_config(self, /) -> QuantizationConfigType | None: ...
    @property
    def search_pool_core(self, /) -> int | None: ...
    @property
    def sparse_vectors(self, /) -> dict[str, EdgeSparseVectorParams]: ...
    @property
    def vectors(self, /) -> dict[str, EdgeVectorParams]: ...

@final
class EdgeOptimizersConfig:
    def __new__(
        cls,
        /,
        deleted_threshold: float | None = None,
        vacuum_min_vector_number: int | None = None,
        default_segment_number: int | None = None,
        max_segment_size: int | None = None,
        indexing_threshold: int | None = None,
        prevent_unoptimized: bool | None = None,
    ) -> EdgeOptimizersConfig: ...
    def __repr__(self, /) -> str: ...
    @property
    def default_segment_number(self, /) -> int | None: ...
    @property
    def deleted_threshold(self, /) -> float | None: ...
    @property
    def indexing_threshold(self, /) -> int | None: ...
    @property
    def max_segment_size(self, /) -> int | None: ...
    @property
    def prevent_unoptimized(self, /) -> bool | None: ...
    @property
    def vacuum_min_vector_number(self, /) -> int | None: ...

@final
class EdgeShard:
    def close(self, /) -> None: ...
    def count(self, /, count: CountRequest) -> int: ...
    @staticmethod
    def create(path: str | PathLike[str], config: EdgeConfig) -> EdgeShard:
        """
        Create a new edge shard at `path` with the given configuration.
        Fails if the path already contains segment data.
        """

    def facet(self, /, facet: FacetRequest) -> FacetResponse: ...
    def flush(self, /) -> None: ...
    def info(self, /) -> ShardInfo: ...
    @staticmethod
    def load(path: str | PathLike[str], config: EdgeConfig | None = None) -> EdgeShard:
        """
        Load an edge shard from existing files at `path`.
        Optional `config`: if provided, compatibility is checked and config is overwritten on disk.
        """

    def optimize(self, /) -> bool: ...
    def query(self, /, query: QueryRequest) -> list[ScoredPoint]: ...
    def query_batch(self, /, request: QueryBatchRequest) -> list[list[ScoredPoint]]:
        """
        Execute several queries as one planned batch.

        Cheaper than one `query` per request: the batch shares a single pass over the segments.
        Returns one result list per request, in the same order as `request.queries`.
        """

    def retrieve(
        self,
        /,
        point_ids: Sequence[PointId],
        with_payload: WithPayloadType | None,
        with_vector: WithVectorType | None,
    ) -> list[Record]: ...
    def scroll(
        self, /, scroll: ScrollRequest
    ) -> tuple[list[Record], PointId | None]: ...
    def search(self, /, search: SearchRequest) -> list[ScoredPoint]: ...
    def snapshot_manifest(self, /) -> Any: ...
    @staticmethod
    def unpack_snapshot(
        snapshot_path: str | PathLike[str], target_path: str | PathLike[str]
    ) -> None: ...
    def update(self, /, operation: UpdateOperation) -> None: ...
    def update_from_snapshot(
        self,
        /,
        snapshot_path: str | PathLike[str],
        tmp_dir: str | PathLike[str] | None = None,
    ) -> None: ...

@final
class EdgeSparseVectorParams:
    def __new__(
        cls,
        /,
        full_scan_threshold: int | None = None,
        on_disk: bool | None = None,
        modifier: Modifier | None = None,
        datatype: VectorStorageDatatype | None = None,
    ) -> EdgeSparseVectorParams: ...
    def __repr__(self, /) -> str: ...
    @property
    def datatype(self, /) -> VectorStorageDatatype | None: ...
    @property
    def full_scan_threshold(self, /) -> int | None: ...
    @property
    def modifier(self, /) -> Modifier | None: ...
    @property
    def on_disk(self, /) -> bool | None: ...

@final
class EdgeVectorParams:
    def __new__(
        cls,
        /,
        size: int,
        distance: Distance,
        on_disk: bool | None = None,
        multivector_config: MultiVectorConfig | None = None,
        datatype: VectorStorageDatatype | None = None,
        quantization_config: QuantizationConfigType | None = None,
        hnsw_config: HnswIndexConfig | None = None,
    ) -> EdgeVectorParams: ...
    def __repr__(self, /) -> str: ...
    @property
    def datatype(self, /) -> VectorStorageDatatype | None: ...
    @property
    def distance(self, /) -> Distance: ...
    @property
    def hnsw_config(self, /) -> HnswIndexConfig | None: ...
    @property
    def multivector_config(self, /) -> MultiVectorConfig | None: ...
    @property
    def on_disk(self, /) -> bool | None: ...
    @property
    def quantization_config(self, /) -> QuantizationConfigType | None: ...
    @property
    def size(self, /) -> int: ...

class Expression:
    @final
    class Abs(Expression):
        __match_args__: Final = ("expr",)
        def __new__(cls, /, expr: Expression) -> Expression.Abs: ...
        @property
        def expr(self, /) -> Expression: ...

    @final
    class Acosh(Expression):
        __match_args__: Final = ("expr",)
        def __new__(cls, /, expr: Expression) -> Expression.Acosh: ...
        @property
        def expr(self, /) -> Expression: ...

    @final
    class Condition(Expression):
        __match_args__: Final = ("cond",)
        def __new__(cls, /, cond: ConditionType) -> Expression.Condition: ...
        @property
        def cond(self, /) -> ConditionType: ...

    @final
    class Constant(Expression):
        __match_args__: Final = ("val",)
        def __new__(cls, /, val: float) -> Expression.Constant: ...
        @property
        def val(self, /) -> float: ...

    @final
    class Datetime(Expression):
        __match_args__: Final = ("date_time",)
        def __new__(cls, /, date_time: str) -> Expression.Datetime: ...
        @property
        def date_time(self, /) -> str: ...

    @final
    class DatetimeKey(Expression):
        __match_args__: Final = ("path",)
        def __new__(cls, /, path: JsonPath) -> Expression.DatetimeKey: ...
        @property
        def path(self, /) -> JsonPath: ...

    @final
    class Decay(Expression):
        __match_args__: Final = ("kind", "x", "target", "midpoint", "scale")
        def __new__(
            cls,
            /,
            kind: DecayKind,
            x: Expression,
            target: Expression | None,
            midpoint: float | None,
            scale: float | None,
        ) -> Expression.Decay: ...
        @property
        def kind(self, /) -> DecayKind: ...
        @property
        def midpoint(self, /) -> float | None: ...
        @property
        def scale(self, /) -> float | None: ...
        @property
        def target(self, /) -> Expression | None: ...
        @property
        def x(self, /) -> Expression: ...

    @final
    class Div(Expression):
        __match_args__: Final = ("left", "right", "by_zero_default")
        def __new__(
            cls, /, left: Expression, right: Expression, by_zero_default: float | None
        ) -> Expression.Div: ...
        @property
        def by_zero_default(self, /) -> float | None: ...
        @property
        def left(self, /) -> Expression: ...
        @property
        def right(self, /) -> Expression: ...

    @final
    class Exp(Expression):
        __match_args__: Final = ("expr",)
        def __new__(cls, /, expr: Expression) -> Expression.Exp: ...
        @property
        def expr(self, /) -> Expression: ...

    @final
    class GeoDistance(Expression):
        __match_args__: Final = ("origin", "to")
        def __new__(
            cls, /, origin: GeoPoint, to: JsonPath
        ) -> Expression.GeoDistance: ...
        @property
        def origin(self, /) -> GeoPoint: ...
        @property
        def to(self, /) -> JsonPath: ...

    @final
    class Ln(Expression):
        __match_args__: Final = ("expr",)
        def __new__(cls, /, expr: Expression) -> Expression.Ln: ...
        @property
        def expr(self, /) -> Expression: ...

    @final
    class Log10(Expression):
        __match_args__: Final = ("expr",)
        def __new__(cls, /, expr: Expression) -> Expression.Log10: ...
        @property
        def expr(self, /) -> Expression: ...

    @final
    class Max(Expression):
        __match_args__: Final = ("exprs",)
        def __new__(cls, /, exprs: Sequence[Expression]) -> Expression.Max: ...
        @property
        def exprs(self, /) -> list[Expression]: ...

    @final
    class Min(Expression):
        __match_args__: Final = ("exprs",)
        def __new__(cls, /, exprs: Sequence[Expression]) -> Expression.Min: ...
        @property
        def exprs(self, /) -> list[Expression]: ...

    @final
    class Mult(Expression):
        __match_args__: Final = ("exprs",)
        def __new__(cls, /, exprs: Sequence[Expression]) -> Expression.Mult: ...
        @property
        def exprs(self, /) -> list[Expression]: ...

    @final
    class Neg(Expression):
        __match_args__: Final = ("expr",)
        def __new__(cls, /, expr: Expression) -> Expression.Neg: ...
        @property
        def expr(self, /) -> Expression: ...

    @final
    class Pow(Expression):
        __match_args__: Final = ("base", "exponent")
        def __new__(
            cls, /, base: Expression, exponent: Expression
        ) -> Expression.Pow: ...
        @property
        def base(self, /) -> Expression: ...
        @property
        def exponent(self, /) -> Expression: ...

    @final
    class Sqrt(Expression):
        __match_args__: Final = ("expr",)
        def __new__(cls, /, expr: Expression) -> Expression.Sqrt: ...
        @property
        def expr(self, /) -> Expression: ...

    @final
    class Sum(Expression):
        __match_args__: Final = ("exprs",)
        def __new__(cls, /, exprs: Sequence[Expression]) -> Expression.Sum: ...
        @property
        def exprs(self, /) -> list[Expression]: ...

    @final
    class Variable(Expression):
        __match_args__: Final = ("var",)
        def __new__(cls, /, var: str) -> Expression.Variable: ...
        @property
        def var(self, /) -> str: ...

@final
class FacetHit:
    def __repr__(self, /) -> str: ...
    @property
    def count(self, /) -> int: ...
    @property
    def value(self, /) -> str | int | bool: ...

@final
class FacetRequest:
    def __new__(
        cls,
        /,
        key: JsonPath,
        limit: int = 10,
        exact: bool = False,
        filter: Filter | None = None,
    ) -> FacetRequest: ...
    @property
    def exact(self, /) -> bool: ...
    @property
    def filter(self, /) -> Filter | None: ...
    @property
    def key(self, /) -> JsonPath: ...
    @property
    def limit(self, /) -> int: ...

@final
class FacetResponse:
    def __iter__(self, /) -> Iterator[FacetHit]: ...
    def __len__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...
    @property
    def hits(self, /) -> list[FacetHit]: ...

@final
class FeedbackItem:
    def __new__(cls, /, vector: NamedVector, score: float) -> FeedbackItem: ...
    def __repr__(self, /) -> str: ...
    @property
    def score(self, /) -> float: ...
    @property
    def vector(self, /) -> NamedVector: ...

@final
class FeedbackNaiveQuery:
    def __new__(
        cls,
        /,
        target: NamedVector,
        feedback: Sequence[FeedbackItem],
        strategy: NaiveFeedbackStrategy,
    ) -> FeedbackNaiveQuery: ...
    def __repr__(self, /) -> str: ...
    @property
    def coefficients(self, /) -> NaiveFeedbackStrategy: ...
    @property
    def feedback(self, /) -> list[FeedbackItem]: ...
    @property
    def target(self, /) -> NamedVector: ...

@final
class FieldCondition:
    def __new__(
        cls,
        /,
        key: JsonPath,
        match: MatchType | None = None,
        range: RangeFloat | RangeDateTime | None = None,
        geo_bounding_box: GeoBoundingBox | None = None,
        geo_radius: GeoRadius | None = None,
        geo_polygon: GeoPolygon | None = None,
        values_count: ValuesCount | None = None,
        is_empty: bool | None = None,
        is_null: bool | None = None,
    ) -> FieldCondition: ...
    @property
    def geo_bounding_box(self, /) -> GeoBoundingBox | None: ...
    @property
    def geo_polygon(self, /) -> GeoPolygon | None: ...
    @property
    def geo_radius(self, /) -> GeoRadius | None: ...
    @property
    def is_empty(self, /) -> bool | None: ...
    @property
    def is_null(self, /) -> bool | None: ...
    @property
    def key(self, /) -> JsonPath: ...
    @property
    def match(self, /) -> MatchType | None: ...
    @property
    def range(self, /) -> RangeFloat | RangeDateTime | None: ...
    @property
    def values_count(self, /) -> ValuesCount | None: ...

@final
class Filter:
    def __new__(
        cls,
        /,
        must: Sequence[ConditionType] | None = None,
        should: Sequence[ConditionType] | None = None,
        must_not: Sequence[ConditionType] | None = None,
        min_should: MinShould | None = None,
    ) -> Filter: ...
    def __repr__(self, /) -> str: ...
    @property
    def min_should(self, /) -> MinShould | None: ...
    @property
    def must(self, /) -> list[ConditionType] | None: ...
    @property
    def must_not(self, /) -> list[ConditionType] | None: ...
    @property
    def should(self, /) -> list[ConditionType] | None: ...

@final
class FloatIndexParams:
    def __new__(
        cls,
        /,
        is_principal: bool | None = None,
        on_disk: bool | None = None,
        enable_hnsw: bool | None = None,
    ) -> FloatIndexParams: ...
    @property
    def enable_hnsw(self, /) -> bool | None: ...
    @property
    def is_principal(self, /) -> bool | None: ...
    @property
    def on_disk(self, /) -> bool | None: ...

@final
class Formula:
    def __new__(
        cls, /, formula: Expression, defaults: dict[str, Any] | None = None
    ) -> Formula: ...
    def __repr__(self, /) -> str: ...

class Fusion:
    def __repr__(self, /) -> str: ...
    @final
    class Dbsf(Fusion):
        __match_args__: Final = ()
        def __new__(cls, /) -> Fusion.Dbsf: ...

    @final
    class Rrf(Fusion):
        __match_args__: Final = ("k", "weights")
        def __new__(
            cls, /, k: int, weights: Sequence[float] | None = None
        ) -> Fusion.Rrf: ...
        @property
        def k(self, /) -> int: ...
        @property
        def weights(self, /) -> list[float] | None: ...

@final
class GeoBoundingBox:
    def __new__(
        cls, /, top_left: GeoPoint, bottom_right: GeoPoint
    ) -> GeoBoundingBox: ...
    def __repr__(self, /) -> str: ...
    @property
    def bottom_right(self, /) -> GeoPoint: ...
    @property
    def top_left(self, /) -> GeoPoint: ...

@final
class GeoIndexParams:
    def __new__(
        cls, /, on_disk: bool | None = None, enable_hnsw: bool | None = None
    ) -> GeoIndexParams: ...
    @property
    def enable_hnsw(self, /) -> bool | None: ...
    @property
    def on_disk(self, /) -> bool | None: ...

@final
class GeoPoint:
    def __new__(cls, /, lon: float, lat: float) -> GeoPoint: ...
    def __repr__(self, /) -> str: ...
    @property
    def lat(self, /) -> float: ...
    @property
    def lon(self, /) -> float: ...

@final
class GeoPolygon:
    def __new__(
        cls,
        /,
        exterior: GeoLineString,
        interiors: Sequence[GeoLineString] | None = None,
    ) -> GeoPolygon: ...
    def __repr__(self, /) -> str: ...
    @property
    def exterior(self, /) -> GeoLineString: ...
    @property
    def interiors(self, /) -> list[GeoLineString] | None: ...

@final
class GeoRadius:
    def __new__(cls, /, center: GeoPoint, radius: float) -> GeoRadius: ...
    def __repr__(self, /) -> str: ...
    @property
    def center(self, /) -> GeoPoint: ...
    @property
    def radius(self, /) -> float: ...

@final
class HasIdCondition:
    def __new__(cls, /, point_ids: set[PointId]) -> HasIdCondition: ...
    def __repr__(self, /) -> str: ...
    @property
    def point_ids(self, /) -> set[PointId]: ...

@final
class HasVectorCondition:
    def __new__(cls, /, vector: str) -> HasVectorCondition: ...
    def __repr__(self, /) -> str: ...
    @property
    def vector(self, /) -> str: ...

@final
class HnswIndexConfig:
    def __new__(
        cls,
        /,
        m: int,
        ef_construct: int,
        full_scan_threshold: int,
        max_indexing_threads: int = 0,
        on_disk: bool | None = None,
        payload_m: int | None = None,
        inline_storage: bool | None = None,
    ) -> HnswIndexConfig: ...
    def __repr__(self, /) -> str: ...
    @property
    def ef_construct(self, /) -> int: ...
    @property
    def full_scan_threshold(self, /) -> int: ...
    @property
    def inline_storage(self, /) -> bool | None: ...
    @property
    def m(self, /) -> int: ...
    @property
    def max_indexing_threads(self, /) -> int: ...
    @property
    def on_disk(self, /) -> bool | None: ...
    @property
    def payload_m(self, /) -> int | None: ...

@final
class IdfParams:
    def __new__(cls, /, corpus: Filter | None = None) -> IdfParams: ...
    def __repr__(self, /) -> str: ...
    @property
    def corpus(self, /) -> Filter | None: ...

@final
class IntegerIndexParams:
    def __new__(
        cls,
        /,
        lookup: bool | None = None,
        range: bool | None = None,
        is_principal: bool | None = None,
        on_disk: bool | None = None,
        enable_hnsw: bool | None = None,
    ) -> IntegerIndexParams: ...
    @property
    def enable_hnsw(self, /) -> bool | None: ...
    @property
    def is_principal(self, /) -> bool | None: ...
    @property
    def lookup(self, /) -> bool | None: ...
    @property
    def on_disk(self, /) -> bool | None: ...
    @property
    def range(self, /) -> bool | None: ...

@final
class IsEmptyCondition:
    def __new__(cls, /, key: JsonPath) -> IsEmptyCondition: ...
    def __repr__(self, /) -> str: ...
    @property
    def key(self, /) -> JsonPath: ...

@final
class IsNullCondition:
    def __new__(cls, /, key: JsonPath) -> IsNullCondition: ...
    def __repr__(self, /) -> str: ...
    @property
    def key(self, /) -> JsonPath: ...

@final
class KeywordIndexParams:
    def __new__(
        cls,
        /,
        is_tenant: bool | None = None,
        on_disk: bool | None = None,
        enable_hnsw: bool | None = None,
        prefix: bool | None = None,
    ) -> KeywordIndexParams: ...
    @property
    def enable_hnsw(self, /) -> bool | None: ...
    @property
    def is_tenant(self, /) -> bool | None: ...
    @property
    def on_disk(self, /) -> bool | None: ...
    @property
    def prefix(self, /) -> bool | None: ...

@final
class Language:
    Arabic: Final[Language]
    Azerbaijani: Final[Language]
    Basque: Final[Language]
    Bengali: Final[Language]
    Catalan: Final[Language]
    Chinese: Final[Language]
    Danish: Final[Language]
    Dutch: Final[Language]
    English: Final[Language]
    Finnish: Final[Language]
    French: Final[Language]
    German: Final[Language]
    Greek: Final[Language]
    Hebrew: Final[Language]
    Hinglish: Final[Language]
    Hungarian: Final[Language]
    Indonesian: Final[Language]
    Italian: Final[Language]
    Japanese: Final[Language]
    Kazakh: Final[Language]
    Nepali: Final[Language]
    Norwegian: Final[Language]
    Portuguese: Final[Language]
    Romanian: Final[Language]
    Russian: Final[Language]
    Slovene: Final[Language]
    Spanish: Final[Language]
    Swedish: Final[Language]
    Tajik: Final[Language]
    Turkish: Final[Language]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class MatchAny:
    def __new__(cls, /, any: list[str] | list[int]) -> MatchAny: ...
    def __repr__(self, /) -> str: ...
    @property
    def value(self, /) -> list[str] | list[int]: ...

@final
class MatchExcept:
    def __new__(cls, /, value: list[str] | list[int]) -> MatchExcept: ...
    def __repr__(self, /) -> str: ...
    @property
    def value(self, /) -> list[str] | list[int]: ...

@final
class MatchPhrase:
    def __new__(cls, /, phrase: str) -> MatchPhrase: ...
    def __repr__(self, /) -> str: ...
    @property
    def phrase(self, /) -> str: ...

@final
class MatchPrefix:
    def __new__(cls, /, prefix: str) -> MatchPrefix: ...
    def __repr__(self, /) -> str: ...
    @property
    def prefix(self, /) -> str: ...

@final
class MatchSubstring:
    def __new__(cls, /, substring: str) -> MatchSubstring: ...
    def __repr__(self, /) -> str: ...
    @property
    def substring(self, /) -> str: ...

@final
class MatchText:
    def __new__(cls, /, text: str) -> MatchText: ...
    def __repr__(self, /) -> str: ...
    @property
    def text(self, /) -> str: ...

@final
class MatchTextAny:
    def __new__(cls, /, text_any: str) -> MatchTextAny: ...
    def __repr__(self, /) -> str: ...
    @property
    def text_any(self, /) -> str: ...

@final
class MatchValue:
    def __new__(cls, /, value: str | int | bool) -> MatchValue: ...
    @property
    def value(self, /) -> str | int | bool: ...

@final
class MinShould:
    def __new__(
        cls, /, conditions: Sequence[ConditionType], min_count: int
    ) -> MinShould: ...
    def __repr__(self, /) -> str: ...
    @property
    def conditions(self, /) -> list[ConditionType]: ...
    @property
    def min_count(self, /) -> int: ...

@final
class Mmr:
    def __new__(
        cls,
        /,
        vector: NamedVector,
        lambda_: float,
        candidates_limit: int,
        using: str | None = None,
    ) -> Mmr: ...
    def __repr__(self, /) -> str: ...
    @property
    def candidates_limit(self, /) -> int: ...
    @property
    def lambda_(self, /) -> float: ...
    @property
    def using(self, /) -> str: ...
    @property
    def vector(self, /) -> NamedVector: ...

@final
class Modifier:
    Idf: Final[Modifier]
    None_: Final[Modifier]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class MultiVectorComparator:
    MaxSim: Final[MultiVectorComparator]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class MultiVectorConfig:
    def __new__(cls, /, comparator: MultiVectorComparator) -> MultiVectorConfig: ...
    def __repr__(self, /) -> str: ...
    @property
    def comparator(self, /) -> MultiVectorComparator: ...

@final
class NaiveFeedbackStrategy:
    def __new__(cls, /, a: float, b: float, c: float) -> NaiveFeedbackStrategy: ...
    def __repr__(self, /) -> str: ...
    @property
    def a(self, /) -> float: ...
    @property
    def b(self, /) -> float: ...
    @property
    def c(self, /) -> float: ...

@final
class NestedCondition:
    def __new__(cls, /, key: JsonPath, filter: Filter) -> NestedCondition: ...
    def __repr__(self, /) -> str: ...
    @property
    def filter(self, /) -> Filter: ...
    @property
    def key(self, /) -> JsonPath: ...

@final
class OrderBy:
    def __new__(
        cls,
        /,
        key: JsonPath,
        direction: Direction | None = None,
        start_from: StartFromType | None = None,
    ) -> OrderBy: ...
    def __repr__(self, /) -> str: ...
    @property
    def direction(self, /) -> Direction | None: ...
    @property
    def key(self, /) -> JsonPath: ...
    @property
    def start_from(self, /) -> StartFromType | None: ...

@final
class PayloadIndexInfo:
    @property
    def data_type(self, /) -> PayloadSchemaType: ...
    @property
    def params(self, /) -> PayloadSchemaParams | None: ...
    @property
    def points(self, /) -> int: ...

@final
class PayloadSchemaType:
    Bool: Final[PayloadSchemaType]
    Datetime: Final[PayloadSchemaType]
    Float: Final[PayloadSchemaType]
    Geo: Final[PayloadSchemaType]
    Integer: Final[PayloadSchemaType]
    Keyword: Final[PayloadSchemaType]
    Text: Final[PayloadSchemaType]
    Uuid: Final[PayloadSchemaType]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

class PayloadSelector:
    @final
    class Exclude(PayloadSelector):
        __match_args__: Final = ("keys",)
        def __new__(cls, /, keys: Sequence[JsonPath]) -> PayloadSelector.Exclude: ...
        @property
        def keys(self, /) -> list[JsonPath]: ...

    @final
    class Include(PayloadSelector):
        __match_args__: Final = ("keys",)
        def __new__(cls, /, keys: Sequence[JsonPath]) -> PayloadSelector.Include: ...
        @property
        def keys(self, /) -> list[JsonPath]: ...

@final
class PlainIndexConfig:
    def __new__(cls, /) -> PlainIndexConfig: ...
    def __repr__(self, /) -> str: ...

@final
class Point:
    def __new__(
        cls, /, id: PointId, vector: Vector, payload: Payload | None = None
    ) -> Point: ...
    def __repr__(self, /) -> str: ...
    @property
    def id(self, /) -> PointId: ...
    @property
    def payload(self, /) -> Payload | None: ...
    @property
    def vector(self, /) -> Vector: ...

@final
class PointVectors:
    def __new__(cls, /, id: PointId, vector: Vector) -> PointVectors: ...
    def __repr__(self, /) -> str: ...
    @property
    def id(self, /) -> PointId: ...
    @property
    def vector(self, /) -> Vector: ...

@final
class Prefetch:
    def __new__(
        cls,
        /,
        limit: int,
        query: ScoringQueryType | None = None,
        prefetches: Sequence[Prefetch] | None = None,
        params: SearchParams | None = None,
        filter: Filter | None = None,
        score_threshold: float | None = None,
    ) -> Prefetch: ...
    def __repr__(self, /) -> str: ...
    @property
    def filter(self, /) -> Filter | None: ...
    @property
    def limit(self, /) -> int: ...
    @property
    def params(self, /) -> SearchParams | None: ...
    @property
    def prefetches(self, /) -> list[Prefetch]: ...
    @property
    def query(self, /) -> ScoringQueryType | None: ...
    @property
    def score_threshold(self, /) -> float | None: ...

@final
class ProductQuantizationConfig:
    def __new__(
        cls, /, compression: CompressionRatio, always_ram: bool | None = None
    ) -> ProductQuantizationConfig: ...
    def __repr__(self, /) -> str: ...
    @property
    def always_ram(self, /) -> bool | None: ...
    @property
    def compression(self, /) -> CompressionRatio: ...

@final
class QuantizationSearchParams:
    def __new__(
        cls,
        /,
        ignore: bool = False,
        rescore: bool | None = None,
        oversampling: float | None = None,
    ) -> QuantizationSearchParams: ...
    def __repr__(self, /) -> str: ...
    @property
    def ignore(self, /) -> bool: ...
    @property
    def oversampling(self, /) -> float | None: ...
    @property
    def rescore(self, /) -> bool | None: ...

class Query:
    def __repr__(self, /) -> str: ...
    @final
    class Context(Query):
        __match_args__: Final = ("query", "using")
        def __new__(
            cls, /, query: ContextQuery, using: str | None = None
        ) -> Query.Context: ...
        @property
        def query(self, /) -> ContextQuery: ...
        @property
        def using(self, /) -> str | None: ...

    @final
    class Discover(Query):
        __match_args__: Final = ("query", "using")
        def __new__(
            cls, /, query: DiscoverQuery, using: str | None = None
        ) -> Query.Discover: ...
        @property
        def query(self, /) -> DiscoverQuery: ...
        @property
        def using(self, /) -> str | None: ...

    @final
    class FeedbackNaive(Query):
        __match_args__: Final = ("query", "using")
        def __new__(
            cls, /, query: FeedbackNaiveQuery, using: str | None = None
        ) -> Query.FeedbackNaive: ...
        @property
        def query(self, /) -> FeedbackNaiveQuery: ...
        @property
        def using(self, /) -> str | None: ...

    @final
    class Nearest(Query):
        __match_args__: Final = ("query", "using")
        def __new__(
            cls, /, query: NamedVector, using: str | None = None
        ) -> Query.Nearest: ...
        @property
        def query(self, /) -> NamedVector: ...
        @property
        def using(self, /) -> str | None: ...

    @final
    class RecommendBestScore(Query):
        __match_args__: Final = ("query", "using")
        def __new__(
            cls, /, query: RecommendQuery, using: str | None = None
        ) -> Query.RecommendBestScore: ...
        @property
        def query(self, /) -> RecommendQuery: ...
        @property
        def using(self, /) -> str | None: ...

    @final
    class RecommendSumScores(Query):
        __match_args__: Final = ("query", "using")
        def __new__(
            cls, /, query: RecommendQuery, using: str | None = None
        ) -> Query.RecommendSumScores: ...
        @property
        def query(self, /) -> RecommendQuery: ...
        @property
        def using(self, /) -> str | None: ...

@final
class QueryBatchRequest:
    """
    Queries executed together as one planned batch.
    """

    def __new__(cls, /, queries: Sequence[QueryRequest]) -> QueryBatchRequest: ...
    def __repr__(self, /) -> str: ...
    @property
    def queries(self, /) -> list[QueryRequest]: ...

@final
class QueryRequest:
    def __new__(
        cls,
        /,
        limit: int,
        offset: int | None = None,
        query: ScoringQueryType | None = None,
        prefetches: Sequence[Prefetch] | None = None,
        with_vector: WithVectorType | None = None,
        with_payload: WithPayloadType | None = None,
        filter: Filter | None = None,
        score_threshold: float | None = None,
        params: SearchParams | None = None,
    ) -> QueryRequest: ...
    def __repr__(self, /) -> str: ...
    @property
    def filter(self, /) -> Filter | None: ...
    @property
    def limit(self, /) -> int: ...
    @property
    def offset(self, /) -> int: ...
    @property
    def params(self, /) -> SearchParams | None: ...
    @property
    def prefetches(self, /) -> list[Prefetch]: ...
    @property
    def query(self, /) -> ScoringQueryType | None: ...
    @property
    def score_threshold(self, /) -> float | None: ...
    @property
    def with_payload(self, /) -> WithPayloadType: ...
    @property
    def with_vector(self, /) -> WithVectorType: ...

@final
class RangeDateTime:
    def __new__(
        cls,
        /,
        gte: str | None = None,
        gt: str | None = None,
        lte: str | None = None,
        lt: str | None = None,
    ) -> RangeDateTime: ...
    @property
    def gt(self, /) -> str | None: ...
    @property
    def gte(self, /) -> str | None: ...
    @property
    def lt(self, /) -> str | None: ...
    @property
    def lte(self, /) -> str | None: ...

@final
class RangeFloat:
    def __new__(
        cls,
        /,
        gte: float | None = None,
        gt: float | None = None,
        lte: float | None = None,
        lt: float | None = None,
    ) -> RangeFloat: ...
    @property
    def gt(self, /) -> float | None: ...
    @property
    def gte(self, /) -> float | None: ...
    @property
    def lt(self, /) -> float | None: ...
    @property
    def lte(self, /) -> float | None: ...

@final
class RecommendQuery:
    def __new__(
        cls, /, positives: Sequence[NamedVector], negatives: Sequence[NamedVector]
    ) -> RecommendQuery: ...
    def __repr__(self, /) -> str: ...
    @property
    def negatives(self, /) -> list[NamedVector]: ...
    @property
    def positives(self, /) -> list[NamedVector]: ...

@final
class Record:
    def __repr__(self, /) -> str: ...
    @property
    def id(self, /) -> PointId: ...
    @property
    def order_value(self, /) -> int | float | None: ...
    @property
    def payload(self, /) -> Payload | None: ...
    @property
    def vector(self, /) -> Vector | None: ...

@final
class Sample:
    Random: Final[Sample]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class ScalarQuantizationConfig:
    def __new__(
        cls,
        /,
        type: ScalarType,
        quantile: float | None = None,
        always_ram: bool | None = None,
    ) -> ScalarQuantizationConfig: ...
    def __repr__(self, /) -> str: ...
    @property
    def always_ram(self, /) -> bool | None: ...
    @property
    def quantile(self, /) -> float | None: ...
    @property
    def type(self, /) -> ScalarType: ...

@final
class ScalarType:
    Int8: Final[ScalarType]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class ScoredPoint:
    def __repr__(self, /) -> str: ...
    @property
    def id(self, /) -> PointId: ...
    @property
    def order_value(self, /) -> int | float | None: ...
    @property
    def payload(self, /) -> Payload | None: ...
    @property
    def score(self, /) -> float: ...
    @property
    def vector(self, /) -> Vector | None: ...
    @property
    def version(self, /) -> int: ...

@final
class ScrollRequest:
    def __new__(
        cls,
        /,
        offset: PointId | None = None,
        limit: int | None = None,
        filter: Filter | None = None,
        with_payload: WithPayloadType | None = None,
        with_vector: WithVectorType | None = None,
        order_by: OrderBy | None = None,
    ) -> ScrollRequest: ...
    def __repr__(self, /) -> str: ...
    @property
    def filter(self, /) -> Filter | None: ...
    @property
    def limit(self, /) -> int | None: ...
    @property
    def offset(self, /) -> PointId | None: ...
    @property
    def order_by(self, /) -> OrderBy | None: ...
    @property
    def with_payload(self, /) -> WithPayloadType | None: ...
    @property
    def with_vector(self, /) -> WithVectorType: ...

@final
class SearchParams:
    def __new__(
        cls,
        /,
        hnsw_ef: int | None = None,
        exact: bool = False,
        quantization: QuantizationSearchParams | None = None,
        indexed_only: bool = False,
        acorn: AcornSearchParams | None = None,
        idf: IdfParams | None = None,
    ) -> SearchParams: ...
    def __repr__(self, /) -> str: ...
    @property
    def acorn(self, /) -> AcornSearchParams | None: ...
    @property
    def exact(self, /) -> bool: ...
    @property
    def hnsw_ef(self, /) -> int | None: ...
    @property
    def idf(self, /) -> IdfParams | None: ...
    @property
    def indexed_only(self, /) -> bool: ...
    @property
    def quantization(self, /) -> QuantizationSearchParams | None: ...

@final
class SearchRequest:
    def __new__(
        cls,
        /,
        query: Query,
        limit: int,
        offset: int | None = None,
        filter: Filter | None = None,
        params: SearchParams | None = None,
        with_vector: WithVectorType | None = None,
        with_payload: WithPayloadType | None = None,
        score_threshold: float | None = None,
    ) -> SearchRequest: ...
    def __repr__(self, /) -> str: ...
    @property
    def filter(self, /) -> Filter | None: ...
    @property
    def limit(self, /) -> int: ...
    @property
    def offset(self, /) -> int: ...
    @property
    def params(self, /) -> SearchParams | None: ...
    @property
    def query(self, /) -> Query: ...
    @property
    def score_threshold(self, /) -> float | None: ...
    @property
    def with_payload(self, /) -> WithPayloadType | None: ...
    @property
    def with_vector(self, /) -> WithVectorType | None: ...

@final
class ShardInfo:
    def __repr__(self, /) -> str: ...
    @property
    def indexed_vectors_count(self, /) -> int: ...
    @property
    def payload_schema(self, /) -> dict[JsonPath, PayloadIndexInfo]: ...
    @property
    def points_count(self, /) -> int: ...
    @property
    def segments_count(self, /) -> int: ...

@final
class SliceCondition:
    def __new__(cls, /, total: int, index: int) -> SliceCondition: ...
    def __repr__(self, /) -> str: ...
    @property
    def index(self, /) -> int: ...
    @property
    def total(self, /) -> int: ...

@final
class SnowballLanguage:
    Arabic: Final[SnowballLanguage]
    Armenian: Final[SnowballLanguage]
    Danish: Final[SnowballLanguage]
    Dutch: Final[SnowballLanguage]
    English: Final[SnowballLanguage]
    Finnish: Final[SnowballLanguage]
    French: Final[SnowballLanguage]
    German: Final[SnowballLanguage]
    Greek: Final[SnowballLanguage]
    Hungarian: Final[SnowballLanguage]
    Italian: Final[SnowballLanguage]
    Norwegian: Final[SnowballLanguage]
    Portuguese: Final[SnowballLanguage]
    Romanian: Final[SnowballLanguage]
    Russian: Final[SnowballLanguage]
    Spanish: Final[SnowballLanguage]
    Swedish: Final[SnowballLanguage]
    Tamil: Final[SnowballLanguage]
    Turkish: Final[SnowballLanguage]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class SnowballParams:
    def __new__(cls, /, language: SnowballLanguage) -> SnowballParams: ...
    @property
    def language(self, /) -> SnowballLanguage: ...

@final
class SparseVector:
    def __new__(
        cls, /, indices: Sequence[int], values: Sequence[float]
    ) -> SparseVector: ...
    def __repr__(self, /) -> str: ...
    @property
    def indices(self, /) -> list[int]: ...
    @property
    def values(self, /) -> list[float]: ...

@final
class StopwordsSet:
    def __new__(
        cls, /, languages: set[Language] | None = None, custom: set[str] | None = None
    ) -> StopwordsSet: ...
    @property
    def custom(self, /) -> set[str] | None: ...
    @property
    def languages(self, /) -> set[Language] | None: ...

@final
class TextIndexParams:
    def __new__(
        cls,
        /,
        tokenizer: TokenizerType | None = None,
        min_token_len: int | None = None,
        max_token_len: int | None = None,
        lowercase: bool | None = None,
        ascii_folding: bool | None = None,
        phrase_matching: bool | None = None,
        stopwords: Stopwords | None = None,
        on_disk: bool | None = None,
        stemmer: StemmingAlgorithm | None = None,
        enable_hnsw: bool | None = None,
    ) -> TextIndexParams: ...
    @property
    def ascii_folding(self, /) -> bool | None: ...
    @property
    def enable_hnsw(self, /) -> bool | None: ...
    @property
    def lowercase(self, /) -> bool | None: ...
    @property
    def max_token_len(self, /) -> int | None: ...
    @property
    def min_token_len(self, /) -> int | None: ...
    @property
    def on_disk(self, /) -> bool | None: ...
    @property
    def phrase_matching(self, /) -> bool | None: ...
    @property
    def stemmer(self, /) -> StemmingAlgorithm | None: ...
    @property
    def stopwords(self, /) -> Stopwords | None: ...
    @property
    def tokenizer(self, /) -> TokenizerType: ...

@final
class TokenizerType:
    Multilingual: Final[TokenizerType]
    Prefix: Final[TokenizerType]
    Whitespace: Final[TokenizerType]
    Word: Final[TokenizerType]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class TurboQuantBitSize:
    Bits1: Final[TurboQuantBitSize]
    Bits1_5: Final[TurboQuantBitSize]
    Bits2: Final[TurboQuantBitSize]
    Bits4: Final[TurboQuantBitSize]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class TurboQuantQuantizationConfig:
    def __new__(
        cls, /, always_ram: bool | None = None, bits: TurboQuantBitSize | None = None
    ) -> TurboQuantQuantizationConfig: ...
    def __repr__(self, /) -> str: ...
    @property
    def always_ram(self, /) -> bool | None: ...
    @property
    def bits(self, /) -> TurboQuantBitSize | None: ...

@final
class UpdateMode:
    """
    Defines the mode of the upsert operation
    """

    InsertOnly: Final[UpdateMode]
    """
    Only insert new points, do not update existing points
    """
    UpdateOnly: Final[UpdateMode]
    """
    Only update existing points, do not insert new points
    """
    Upsert: Final[UpdateMode]
    """
    Default mode - insert new points, update existing points
    """
    def __eq__(self, value: object, /) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class UpdateOperation:
    @staticmethod
    def clear_payload(point_ids: Sequence[PointId]) -> UpdateOperation: ...
    @staticmethod
    def clear_payload_by_filter(filter: Filter) -> UpdateOperation: ...
    @staticmethod
    def create_dense_vector(
        vector_name: str,
        size: int,
        distance: Distance,
        multivector_config: MultiVectorConfig | None = None,
        datatype: VectorStorageDatatype | None = None,
    ) -> UpdateOperation:
        """
        Create a new dense named vector on the collection.
        """

    @staticmethod
    def create_field_index(
        field_name: JsonPath, schema: PayloadFieldSchema
    ) -> UpdateOperation: ...
    @staticmethod
    def create_sparse_vector(
        vector_name: str,
        modifier: Modifier | None = None,
        datatype: VectorStorageDatatype | None = None,
    ) -> UpdateOperation:
        """
        Create a new sparse named vector on the collection.
        """

    @staticmethod
    def delete_field_index(field_name: JsonPath) -> UpdateOperation: ...
    @staticmethod
    def delete_payload(
        point_ids: Sequence[PointId], keys: Sequence[JsonPath]
    ) -> UpdateOperation: ...
    @staticmethod
    def delete_payload_by_filter(
        filter: Filter, keys: Sequence[JsonPath]
    ) -> UpdateOperation: ...
    @staticmethod
    def delete_points(point_ids: Sequence[PointId]) -> UpdateOperation: ...
    @staticmethod
    def delete_points_by_filter(filter: Filter) -> UpdateOperation: ...
    @staticmethod
    def delete_vector_name(vector_name: str) -> UpdateOperation:
        """
        Delete a named vector from the collection.
        """

    @staticmethod
    def delete_vectors(
        point_ids: Sequence[PointId], vector_names: Sequence[str]
    ) -> UpdateOperation: ...
    @staticmethod
    def delete_vectors_by_filter(
        filter: Filter, vector_names: Sequence[str]
    ) -> UpdateOperation: ...
    @staticmethod
    def overwrite_payload(
        point_ids: Sequence[PointId], payload: Payload, key: JsonPath | None = None
    ) -> UpdateOperation: ...
    @staticmethod
    def overwrite_payload_by_filter(
        filter: Filter, payload: Payload, key: JsonPath | None = None
    ) -> UpdateOperation: ...
    @staticmethod
    def set_payload(
        point_ids: Sequence[PointId], payload: Payload, key: JsonPath | None = None
    ) -> UpdateOperation: ...
    @staticmethod
    def set_payload_by_filter(
        filter: Filter, payload: Payload, key: JsonPath | None = None
    ) -> UpdateOperation: ...
    @staticmethod
    def update_vectors(
        point_vectors: Sequence[PointVectors], condition: Filter | None = None
    ) -> UpdateOperation: ...
    @staticmethod
    def upsert_points(
        points: Sequence[Point],
        condition: Filter | None = None,
        update_mode: UpdateMode | None = None,
    ) -> UpdateOperation: ...

@final
class UuidIndexParams:
    def __new__(
        cls,
        /,
        is_tenant: bool | None = None,
        on_disk: bool | None = None,
        enable_hnsw: bool | None = None,
    ) -> UuidIndexParams: ...
    @property
    def enable_hnsw(self, /) -> bool | None: ...
    @property
    def is_tenant(self, /) -> bool | None: ...
    @property
    def on_disk(self, /) -> bool | None: ...

@final
class ValuesCount:
    def __new__(
        cls,
        /,
        lt: int | None = None,
        gt: int | None = None,
        lte: int | None = None,
        gte: int | None = None,
    ) -> ValuesCount: ...
    def __repr__(self, /) -> str: ...
    @property
    def gt(self, /) -> int | None: ...
    @property
    def gte(self, /) -> int | None: ...
    @property
    def lt(self, /) -> int | None: ...
    @property
    def lte(self, /) -> int | None: ...

@final
class VectorStorageDatatype:
    Float16: Final[VectorStorageDatatype]
    Float32: Final[VectorStorageDatatype]
    Turbo4: Final[VectorStorageDatatype]
    Uint8: Final[VectorStorageDatatype]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

QuantizationConfigType: TypeAlias = (
    ScalarQuantizationConfig
    | ProductQuantizationConfig
    | BinaryQuantizationConfig
    | TurboQuantQuantizationConfig
)
IndexType: TypeAlias = PlainIndexConfig | HnswIndexConfig
ScoringQueryType: TypeAlias = Query | Fusion | OrderBy | Formula | Sample | Mmr
StartFromType: TypeAlias = int | float | str
ConditionType: TypeAlias = (
    FieldCondition
    | IsEmptyCondition
    | IsNullCondition
    | HasIdCondition
    | HasVectorCondition
    | SliceCondition
    | NestedCondition
    | Filter
)
GeoLineString: TypeAlias = Sequence[GeoPoint]
MatchType: TypeAlias = (
    MatchValue
    | MatchText
    | MatchTextAny
    | MatchPhrase
    | MatchPrefix
    | MatchSubstring
    | MatchAny
    | MatchExcept
)
JsonPath: TypeAlias = str
Payload: TypeAlias = dict[str, typing.Any]
PayloadFieldSchema: TypeAlias = PayloadSchemaType | PayloadSchemaParams
PayloadSchemaParams: TypeAlias = (
    KeywordIndexParams
    | IntegerIndexParams
    | FloatIndexParams
    | GeoIndexParams
    | TextIndexParams
    | BoolIndexParams
    | DatetimeIndexParams
    | UuidIndexParams
)
StemmingAlgorithm: TypeAlias = SnowballParams | DisabledStemmer
Stopwords: TypeAlias = Language | StopwordsSet
PointId: TypeAlias = int | uuid.UUID | str
WithPayloadType: TypeAlias = bool | Sequence[JsonPath] | PayloadSelector
WithVectorType: TypeAlias = bool | Sequence[str]
NamedVector: TypeAlias = Sequence[float] | SparseVector | Sequence[Sequence[float]]
Vector: TypeAlias = Sequence[float] | Sequence[Sequence[float]] | dict[str, NamedVector]
