# You can run the following command in the repository root:
# uv tool run codespell --toml tools/codespell.toml

[tool.codespell]

skip = [
    "**/stop_words/*.rs",
    "./static",
    "./tests/e2e_tests/test_data/cert/key.pem",
    "openapi.json", # openapi.json is typically a released version and could carry old typos
    "target",
]

ignore-words-list = [
    "ABD",                 # Geohash example
    "generall",            # The boss
    "hel",                 # Query token
    "mmapped",             # Memory mapped
]
