#version 450

#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_shuffle : enable

#define VECTOR_STORAGE_LAYOUT_SET 0
#define LINKS_LAYOUT_SET 1
#define SEARCHER_LAYOUT_SET 2

#include "vector_storage.comp"
#include "links.comp"
#include "searcher.comp"

layout(set = 3, binding = 0) buffer RequestData {
    POINT_ID data[];
} request;

layout(set = 3, binding = 1) buffer ResponseData {
    POINT_ID data[];
} response;

void main() {
    POINT_ID point_id = request.data[2 * gl_GlobalInvocationID.x];
    POINT_ID entry_id = request.data[2 * gl_GlobalInvocationID.x + 1];
    float score = similarity_obsolete(point_id, entry_id);
    ScoredPoint entry = ScoredPoint(entry_id, score);

    ScoredPoint greedy = greedy_search(point_id, entry);
    response.data[gl_GlobalInvocationID.x] = greedy.id;
}
