#version 450

#define VECTOR_STORAGE_LAYOUT_SET 0
#define LINKS_LAYOUT_SET 1
#define SEARCHER_LAYOUT_SET 2

#include "vector_storage.comp"
#include "links.comp"
#include "searcher.comp"

layout(set = 3, binding = 0) buffer RequestData {
    POINT_ID data[];
} request;

layout(set = 3, binding = 1) buffer ResponseData {
    POINT_ID data[];
} response;

void main() {
    searcher_init();

    POINT_ID point_id = request.data[2 * gl_GlobalInvocationID.x];
    POINT_ID entry_id = request.data[2 * gl_GlobalInvocationID.x + 1];
    float score = similarity(point_id, entry_id);
    ScoredPoint entry = ScoredPoint(entry_id, score);

    search(point_id, entry);

    uint heuristic_size = run_heuristic();
    response.data[gl_GlobalInvocationID.x * (LEVEL_M + 1)] = heuristic_size;

    for (uint i = 0; i < heuristic_size; i += 1) {
        ScoredPoint scored_point = get_nearest(i);
        response.data[gl_GlobalInvocationID.x * (LEVEL_M + 1) + 1 + i] = scored_point.id;
    }
}
