name: Build and push a branch gpu image to ghcr

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  branch-gpu-build-and-push:
    runs-on: [self-hosted, linux, x64]
    steps:
        - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
          with:
            ref: ${{ github.ref_name }}
        - uses: ./.github/actions/branch-build-and-push
          with:
            ghcr-password: ${{ secrets.GITHUB_TOKEN }}
            push-to-ghcr: true
            build-gpu: true
            staging-build: ${{ github.ref_type == 'branch' && github.ref_name != 'master' }}
