name: Qdrant Edge Release Build

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to PyPI'
        type: boolean
        default: false
        required: true


jobs:
  edge-py-linux:
    name: Build Python wheels [Linux]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64, aarch64]
        manylinux: [manylinux_2_17, manylinux_2_28]
        python:
          - python3.10
          - pypy3.11

        include:
          - arch: x86_64
            target: x86_64-unknown-linux-musl
            manylinux: musllinux_1_2
            python: python3.10

          - arch: aarch64
            target: aarch64-unknown-linux-musl
            manylinux: musllinux_1_2
            python: python3.10

        exclude:
          - target: aarch64
            manylinux: manylinux_2_17

    steps:
      - name: Checkout Qdrant
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build Python wheel
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad # v1.50.1
        with:
          command: build
          args: --release --features abi3 --interpreter ${{ matrix.python }} --out dist
          working-directory: lib/edge/python
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.manylinux }}

      - name: Upload Python wheel
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: qdrant-edge-${{ matrix.manylinux }}-${{ matrix.arch || matrix.target }}-${{ matrix.python }}
          path: lib/edge/python/dist


  edge-py-macos:
    name: Build Python wheels [macOS]

    runs-on: macos-latest

    strategy:
      matrix:
        target: [x86_64, aarch64]
        python:
          - label: python3.10
            version: '3.10'
          - pypy3.11

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable

      - name: Install Python
        id: setup-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python.version || matrix.python }}

      - name: Checkout Qdrant
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build Python wheel
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad # v1.50.1
        with:
          command: build
          args: --release --features abi3 --interpreter ${{ steps.setup-python.outputs.python-path }} --out dist
          working-directory: lib/edge/python
          target: ${{ matrix.target }}

      - name: Upload Python wheel
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: qdrant-edge-macos-${{ matrix.target }}-${{ matrix.python.label || matrix.python }}
          path: lib/edge/python/dist


  edge-py-windows:
    name: Build Python wheels [Windows]

    runs-on: windows-latest

    strategy:
      matrix:
        target: [x86_64]
        python:
          - label: python3.10
            version: '3.10'
          - pypy3.11

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable

      - name: Install Python
        id: setup-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python.version || matrix.python }}

      - name: Checkout Qdrant
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build Python wheel
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad # v1.50.1
        with:
          command: build
          args: --release --features abi3 --interpreter ${{ steps.setup-python.outputs.python-path }} --out dist
          working-directory: lib/edge/python
          target: ${{ matrix.target }}

      - name: Upload Python wheel
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: qdrant-edge-windows-${{ matrix.target }}-${{ matrix.python.label || matrix.python }}
          path: lib/edge/python/dist


  edge-py-test:
    name: Test Python wheels [${{ matrix.os }}, ${{ matrix.python }}]

    runs-on: ${{ matrix.os }}
    needs:
      - edge-py-linux
      - edge-py-macos
      - edge-py-windows

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-24.04-arm
          - ubuntu-latest
          - windows-latest
        python:
          - '3.10'
          - 'pypy3.11'

    steps:
      - name: Checkout Qdrant
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python }}

      - name: Download wheels
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: qdrant-edge-*
          merge-multiple: true
          path: lib/edge/python/dist

      - name: Setup Qdrant
        uses: ./.github/actions/setup-qdrant

      - name: Install and test wheel
        working-directory: lib/edge/python
        run: |
          uv venv --allow-existing --python ${{ matrix.python }}
          uv pip install --no-index --find-links dist/ qdrant-edge-py
          uv pip install requests
          just py-examples


  merge-artifacts:
    name: Merge release artifacts

    runs-on: ubuntu-latest
    needs:
      - edge-py-linux
      - edge-py-macos
      - edge-py-windows
      - edge-py-test

    if: inputs.publish

    steps:
      - name: Merge release artifacts
        uses: actions/upload-artifact/merge@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: qdrant-edge
          pattern: qdrant-edge-*
          delete-merged: false


  publish:
    name: Publish to PyPI

    runs-on: ubuntu-latest
    needs:
      - merge-artifacts

    if: inputs.publish

    steps:
      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0

      - name: Download release wheels
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: qdrant-edge

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN_EDGE }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing *
