name: Qdrant Edge Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ '**' ]

jobs:
  edge-test:
    name: Test Qdrant Edge

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # For PRs, only run on ubuntu to save CI time
        os: >-
          ${{
            github.event_name == 'pull_request'
            && fromJSON('["ubuntu-latest"]')
            || fromJSON('["ubuntu-latest", "macos-latest", "windows-latest"]')
          }}

    steps:
      - name: Checkout Qdrant
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust nightly (for fmt)
        uses: dtolnay/rust-toolchain@0f1b44df7e9cbb178d781a242338dfa5e243ad7f # nightly
        with:
          components: rustfmt

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable
        with:
          components: rustfmt, clippy

      - name: Install mold
        if: runner.os == 'Linux'
        uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1

      - name: Enable mold
        if: runner.os == 'Linux'
        run: |
          mkdir .cargo

          cat >.cargo/config.toml <<-EOF
          [target.x86_64-unknown-linux-gnu]
          linker = "clang"
          rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
          EOF

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'

      - name: Install Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Install tools
        run: |
          uv tool install ast-grep-cli
          uv tool install maturin

      - name: Setup Qdrant
        uses: ./.github/actions/setup-qdrant

      - name: Restore Rust build cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Prepare data files
        id: rs-prepare-data
        working-directory: lib/edge
        run: just prepare-data

      - name: 🦀 Check Rust
        working-directory: lib/edge
        run: just rs-check

      - name: 🦀 Build Rust examples
        working-directory: lib/edge
        run: just rs-examples-build

      - name: 🦀 Run Rust examples
        working-directory: lib/edge
        run: just rs-examples

      - name: 🐍 Build Python edge
        working-directory: lib/edge/python
        run: just py-build

      - name: 🐍 Run Python examples
        working-directory: lib/edge
        run: just py-examples

      - name: Check for uncommitted changes
        if: always()
        run: git diff --exit-code
