name: Formatter and linter

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Install minimal nightly (only for fmt)
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - name: Install minimal stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - uses: actions/checkout@v4
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    # Force cmake version for 'shaderc' crate. The runner `ubuntu-latest` has cmake 4.x
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.x'
    - uses: Swatinem/rust-cache@v2
      with:
        key: clippy
    - name: Update apt
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install clang libunwind-dev
    - name: Check code formatting
      run: cargo +nightly fmt --all -- --check
    - name: Check cargo clippy warnings
      run: cargo clippy --workspace -- -D warnings
    - name: Check cargo clippy warnings for all targets
      run: cargo clippy --workspace --all-targets -- -D warnings
    - name: Check cargo clippy warnings for all targets and features
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
